# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3551fac98818d2d7d73375b64651c0cfd46c529b0000d77ed0f037bf97690ee36d7e824dad06373bb2f4f9f322ddce3bdfecf19528eecd56185ff7a31c9940dd

test:
  secret_key_base: fd26710b24652fa903ca181c25c25b9f36069700d8021eb3d0512d9fc51066c912720dddae59f418e067a69c98f0edd695cb7f1c2e6fac5c548f6f586c891559

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
